server:
  port: 8080

jms:
  ibm:
    mq:
      queue-manager: 'QM1'
      transport-type: 1
      channel: 'DEV.ADMIN.SVRCONN'
      host: 'localhost'
      port: 1414
      user: 'admin'
      password: 'passw0rd'
  consumer:
    example:
      queue: 'SYSTEM.DEFAULT.LOCAL.QUEUE'
      concurrency: 1

---
spring:
  profiles: test